const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const {chromium}=require('playwright');
const root=path.resolve('dist');let update=false;
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);let file=path.join(root,pathname==='/'?'index.html':pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}try{let body=fs.readFileSync(file);if(file.endsWith('sw.js')&&update)body=Buffer.from(body.toString().replace('treino-corda-v3-1','treino-corda-v3-1-test-update'));const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'}[path.extname(file)]||'application/octet-stream';res.writeHead(200,{'Content-Type':type,'Cache-Control':'no-store'});res.end(body)}catch{res.writeHead(404).end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;let browser;try{
 browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'America/Sao_Paulo',acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:new Date('2026-09-30T15:00:00-03:00')});await page.addInitScript(()=>{if(!localStorage.getItem('corda-state'))localStorage.setItem('corda-state',JSON.stringify({done:{'2026-09-28-3-0':true,'2026-09-21-0-0':true},notes:'Minha nota antiga',loads:'Carga anterior'}))});await page.goto(url);await page.waitForFunction(()=>navigator.serviceWorker.controller);await page.waitForSelector('.exercise-open');
 assert.equal(await page.locator('#progress').textContent(),'1 de 7 concluídos');await page.locator('#dailyNotes').fill('Boa execução hoje');await page.locator('.exercise-open').first().click();await page.locator('#saveLoad').click();assert.match(await page.locator('#recordedLoad').textContent(),/2,5 kg/);assert.match(await page.locator('#assemblyText').textContent(),/1 × 1,25 kg/);await page.locator('#closeExercise').click();
 await page.selectOption('#dayMode','light');assert.equal(await page.locator('.exercise-row').count(),4);await page.locator('.check').first().check();await page.selectOption('#dayMode','normal');assert.equal(await page.locator('#progress').textContent(),'1 de 7 concluídos');await page.selectOption('#dayMode','light');assert.equal(await page.locator('#progress').textContent(),'1 de 4 concluídos');await page.locator('#unwell').check();assert.equal(await page.locator('.exercise-row').count(),0);assert(await page.locator('#dayMode').isDisabled());assert(await page.locator('#technicalBlock').isHidden());await page.locator('#unwell').uncheck();await page.selectOption('#dayMode','normal');
 await page.locator('#date').click();await page.locator('[data-date="2026-09-27"]').click();assert.equal(await page.locator('#progress').textContent(),'1 de 3 concluídos');assert.equal(await page.locator('#dailyNotes').inputValue(),'');await page.locator('#dailyNotes').fill('Recuperação domingo');await page.locator('[data-target="today"]').click();assert.equal(await page.locator('#dailyNotes').inputValue(),'Boa execução hoje');

 const beforeWeek=await page.evaluate(()=>localStorage.getItem('corda-state'));
 await page.locator('[data-target="week"]').click();assert.equal(await page.locator('#weekDays button').count(),7);assert.match(await page.locator('#weekRange').textContent(),/28 de setembro de 2026 a 4 de outubro de 2026/);
 for(const [date,count] of [['2026-09-28',4],['2026-09-29',4],['2026-09-30',7],['2026-10-01',4],['2026-10-02',7],['2026-10-03',6],['2026-10-04',3]]){await page.locator('[data-week-date="'+date+'"]').click();await page.selectOption('#weeklyMode','normal');assert.equal(await page.locator('#weeklyList article').count(),count);await page.selectOption('#weeklyMode','light');assert.equal(await page.locator('#weeklyList article').count(),4);await page.selectOption('#weeklyMode','rest');assert.equal(await page.locator('#weeklyList article').count(),0);}
 await page.locator('[data-week-date="2026-09-30"]').click();await page.selectOption('#weeklyMode','normal');await page.locator('#weeklyList button').first().click();assert(await page.locator('#saveLoad').isHidden());await page.locator('#closeExercise').click();assert.equal(await page.evaluate(()=>localStorage.getItem('corda-state')),beforeWeek);
 fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/week-mobile.png'});await page.locator('#date').click();assert(await page.locator('#history').isVisible());await page.locator('[data-target="week"]').click();await page.locator('#openWeeklyDate').click();assert.equal(await page.locator('#dailyNotes').inputValue(),'Boa execução hoje');
await page.locator('#dayMusic').click();assert.equal(await page.locator('.music-card').count(),5);await page.locator('[data-music="angola"]').check();await page.locator('[data-target="settings"]').click();assert.equal(await page.locator('#legacyNotes').textContent(),'Minha nota antiga');await page.locator('#barWeight').fill('0.5');const downloadPromise=page.waitForEvent('download');await page.locator('#exportData').click();const download=await downloadPromise;const filename=await download.path();const backup=JSON.parse(fs.readFileSync(filename,'utf8'));assert.equal(backup.state.days['2026-09-30'].notes,'Boa execução hoje');assert(backup.state.days['2026-09-30'].music.angola);assert(backup.state.days['2026-09-30'].sessions.light.done[0]);
 await page.locator('[data-target="today"]').click();await page.locator('.exercise-open').first().click();assert.match(await page.locator('#loadChoice').textContent(),/3 kg por halter/);fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/exercise-mobile.png',fullPage:true});await page.locator('#closeExercise').click();await page.locator('#date').click();await page.screenshot({path:'test-results/calendar-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await context.setOffline(true);await page.reload();await page.locator('.exercise-open').first().click();await page.waitForFunction(()=>Array.from(document.images).every(img=>img.complete&&img.naturalWidth>0));assert.equal(await page.locator('#dailyNotes').inputValue(),'Boa execução hoje');await page.locator('#closeExercise').click();await context.setOffline(false);
 update=true;await page.locator('[data-target="settings"]').click();await page.locator('#checkUpdate').click();await page.locator('#updateBanner').waitFor({state:'visible'});await page.locator('#applyUpdate').click();await page.waitForFunction(()=>navigator.serviceWorker.controller&&document.querySelector('#dailyNotes').value==='Boa execução hoje');await page.waitForFunction(async()=> (await caches.keys()).includes('treino-corda-v3-1-test-update'));assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('corda-state')).legacyNotes),'Minha nota antiga');
 await page.locator('#date').click();await page.locator('#nextMonth').click();await page.locator('[data-date="2026-10-01"]').click();assert(await page.locator('#dailyNotes').isDisabled());assert(await page.locator('#dayMode').isDisabled());await page.locator('[data-target="settings"]').click();page.once('dialog',dialog=>dialog.accept());await page.locator('#importData').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForFunction(()=>document.querySelector('#dailyNotes').value==='Boa execução hoje');await page.setViewportSize({width:320,height:740});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.selectOption('#dayMode','light');await page.screenshot({path:'test-results/light-mobile.png'});await page.locator('#dayMusic').click();await page.screenshot({path:'test-results/music-mobile.png'});assert.deepEqual(errors,[]);console.log('PASS: migração, calendário, cargas, modos normal/leve/descanso, febre, backup, musicalidade, mobile, offline e atualização preservando registros.');
 }finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
